import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/widgets/header/ui/Header";
import { StoreProvider } from "./providers/StoreProvider";
import Navigation from "@/widgets/navigation/ui/Navigation";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Rutube 2.0",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="ru">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen`}
			>
				<div id="portal-root" />
				<StoreProvider>
					<Header />
					<main className="flex min-h-screen pt-[67px]">
						{/* Сайдбар */}
						<Navigation />

						{/* Контент */}
						<div className="p-6 flex-1 overflow-auto">{children}</div>
					</main>
				</StoreProvider>
			</body>
		</html>
	);
}
